### ISSUE TITLE
no services shown

### ISSUE THREAD

**Issue by francescob** [aderyabin/ServPane#2]
on MacOs high Sierra, no brew services are shown in the menubar, but I have at least one on my system (mysql)

**Comment by edwardwang0302** [comment]
It doesn't work with me too. I rebuilt it by myself with devtools enabled. I found error in console like this:
Error: spawn error ENOENT

I used Google to figure out why this happened, and found this airticle: https://serverfault.com/questions/16355/how-to-set-global-path-on-os-x

But I still don't know how fix this problem

@aderyabin  Do u have any idea?

**Comment by edwardwang0302** [comment]
I fixed this problem. I’ll make a pull request later

**Comment by francescob** [comment]
is this project dead already?

**Comment by aderyabin** [comment]
No, I have no time to review your PR. I promise to look at the weekend.

**Comment by coreyjackwilson** [comment]
issue was fixed in https://github.com/aderyabin/ServPane/pull/3

@aderyabin can close.

**Comment by aderyabin** [comment]
Closed at #3
